#!/bin/bash

AMERICANO_PRICE=4000
CAFELATTE_PRICE=5000
AMERICANO_COUNT=4
CAFELATTE_COUNT=6
AMERICANO_TOTAL_PRICE=$(expr $AMERICANO_PRICE \* $AMERICANO_COUNT)
CAFELATTE_TOTAL_PRICE=$(expr $CAFELATTE_PRICE \* $CAFELATTE_COUNT)
TOTAL_PRICE=$(expr $AMERICANO_TOTAL_PRICE + $CAFELATTE_TOTAL_PRICE)
echo 주문한 음료 가격은 ${TOTAL_PRICE}원입니다.
